language: php
php:
  - "7.3"
  - "7.4"
  - "8.0"
  - nightly

install:
  - composer install

notifications:
  email:
    on_success: never
    on_failure: always

after_script:
  - ./vendor/bin/coveralls -v
